baseURL = "http://ashipwithoutacrew.info/"
languageCode = "en-us"
title = "A Ship Without a Crew"
theme = "solar-theme-hugo"
paginate = 3

[menu]
  [[menu.main]]
    name = "Episodes"
    url = "/episodes"
    identifier = "episodes"
    weight = 0

  [[menu.main]]
    name = "Characters"
    url = "/characters"
    weight = 0

  [[menu.main]]
    name = "Locations"
    identifier = "locations"
    url = "/locations"
    weight = 0

    [[menu.main]]
    name = "Loot"
    url = "/loot/loot-list/"

# https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

